### ISSUE TITLE
No screen with TWRP 3.3.1-0-tissot

### ISSUE THREAD

**Issue by ogmkp** [TeamWin/android_device_xiaomi_tissot#4]
Hi.

I have a black screen when i boot twrp 3.3.1-0-tissot img from fastboot but my computer can detect and display the MTP share with the internal storage of the phone.

Do you have solutions ?

Thanks.

**Comment by methuselahin** [comment]
I also faced the similar issue. Just flash with 3.18 kernel image and format data. You will have your internal storage visible. Just boot though. I had issues in looking data contents with official recovery 4.9, only 3.18 kernel recovery was able to look at the data partition.

**Comment by ogmkp** [comment]
Thanks for the answer.

I found a post of nicknitewolf who mention that a new version a TWRP is ready with some bugs corrections.
https://forum.xda-developers.com/mi-a1/development/recovery-twrp-3-2-2-1-touch-recovery-t3821469
I used the kernel 3.18 linked in this post and all is functionnal now, like you said.

Thanks.

**Comment by picblog229** [comment]
So i had this exact same issue. It was booting to twrp but screen was just blank.
i was trying to root the devive so i flashed the zip file by following command through adb

adb shell twrp install /sdcard/Magisk-v23.0.zip

it flashed the magisk and it was done. Similarly you can flash any zip file. If zip file is not copied to internal memory you can copy it using following command
adb push Magisk-v23.0.zip /sdcard/

I hope it helps someone in need.
Thanks.

**Comment by ali32768** [comment]
At last I found a way to run TWRP on tissot correctly without black screen.
Just install oreo 3.2.1-2 on Mi A1 (tissot).
This file (recovery-3.2.1-2-oreo.img) is working well.

Download it from this site:
https://androidfilehost.com/?fid=818070582850498337

Reference:
https://forum.xda-developers.com/t/official-recovery-tissot-twrp-3-2-1-2-oreo-touch-recovery-2018-03-06.3688472/

Download Android 13.00 unofficial ROM for Mi A1 and install it easily by TWRP oreo 3.2.1-2:
https://sourceforge.net/projects/lafactorial-tissot/files/

Good luck,
Sed
